// Generated by CoffeeScript 1.6.2
(function() {
  define(['camera', 'mocha', 'chai'], function(Camera, mocha, chai) {
    var assert;

    assert = chai.assert;
    return suite('Camera', function() {
      var camera;

      camera = new Camera();
      suite('#Camera', function() {
        return test('is instance of Camera', function() {
          return assert.instanceOf(camera, Camera);
        });
      });
      return suite('#take()', function() {
        return test('is function', function() {
          return assert.isFunction(camera.take);
        });
      });
    });
  });

}).call(this);
