// Generated by CoffeeScript 1.6.2
(function() {
  define(function() {
    var Camera;

    return Camera = (function() {
      function Camera() {}

      Camera.prototype.take = function() {};

      return Camera;

    })();
  });

}).call(this);
