// Generated by CoffeeScript 1.6.2
(function() {
  var Camera;

  window.Camera = Camera = (function() {
    function Camera() {}

    Camera.prototype.take = function() {};

    return Camera;

  })();

}).call(this);
